version: '3'
services:
  frontend:
    build:
      context: ./Library.UI
      dockerfile: Dockerfile
    ports:
      - 4200:4200

  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 7019:80
